server:
   port: 7101

logging:
   level:
      root: INFO
      
spring.mvc.converters.preferred-json-mapper: gson

camunda7.rest.oauth.token.uri:
camunda7.rest.oauth.token.clientId:
camunda7.rest.oauth.token.clientSecret:
camunda7.rest.oauth.token.grantType:

camunda7.rest.deployment.url: /deployment
camunda7.rest.processdefinition.url: /process-definition
camunda7.rest.processinstance.url: /process-instance
camunda7.rest.task.url: /task
camunda7.rest.correlate.url: /message

spring.data.mongodb.uri: ${MONGO_CONN:mongodb://localhost}
spring.data.mongodb.database: ${MONGO_SHARED_DATABASE:shared}
spring.data.mongodb.database.tenant: ${MONGO_DATABASE:app}

mongo.data.import.enabled: true
mongo.data.import.folder: ${IMPORT_DIR_PATH:./data}

keycloak.data.import.enabled: true
keycloak.data.import.url: ${KEYCLOAK_URL:http://localhost:8082}
keycloak.data.import.admin: ${KEYCLOAK_ADMIN:admin}
keycloak.data.import.adminpass: ${KEYCLOAK_PASS:admin}
keycloak.data.import.clientid: wks-portal
keycloak.data.import.realm: ${spring.data.mongodb.database.tenant}
keycloak.data.import.dns: ${KEYCLOAK_IMPORT_DNS:localhost}
keycloak.data.import.port: ${KEYCLOAK_IMPORT_PORT}
keycloak.data.import.protocol: ${KEYCLOAK_IMPORT_PROTOCOL:https}
keycloak.data.import.redirecturl: ${keycloak.data.import.protocol}://${keycloak.data.import.dns}${keycloak.data.import.port}/*
keycloak.data.import.weborigins: ${keycloak.data.import.protocol}://${keycloak.data.import.dns}${keycloak.data.import.port}
keycloak.data.import.username: victor
keycloak.data.import.password: victor
keycloak.data.import.firstname: Victor
keycloak.data.import.lastname: Franca
keycloak.data.import.email: victor@gmail.com

camunda.data.import.enabled: true
camunda.data.import.url: ${CAMUNDA_URL:http://localhost:8080/engine-rest}
camunda.data.import.username: ${CAMUNDA_USERNAME:demo}
camunda.data.import.password: ${CAMUNDA_PASSWORD:demo}
camunda.data.import.folder: ${IMPORT_DIR_PATH:./data}
camunda.data.import.tenant: ${spring.data.mongodb.database.tenant}
