server:
   port: 8084

logging:
   level:
      root: INFO
      com:
         wks: INFO
         wks.bpm.engine.camunda: DEBUG
      org.springframework.web.client.RestTemplate: ERROR
      org.apache.http: ERROR
      httpclient.wire: ERROR    

camunda7.rest.oauth.token.uri:
camunda7.rest.oauth.token.clientId:
camunda7.rest.oauth.token.clientSecret:
camunda7.rest.oauth.token.grantType:

camunda7.rest.deployment.url: /deployment
camunda7.rest.processdefinition.url: /process-definition
camunda7.rest.task.url: /task
camunda7.rest.processinstance.url: /process-instance
camunda7.rest.correlate.url: /message

camunda.bpm.client:
  base-url: ${CAMUNDA_URL:http://camunda:8080/engine-rest}
  async-response-timeout: 1000
  disable-backoff-strategy: false
  backoff-strategy-time: 2000
  basic-auth:
    username: ${CAMUNDA_USERNAME:demo}
    password: ${CAMUNDA_PASSWORD:demo}

spring.data.mongodb.uri: ${MONGO_CONN:mongodb://localhost}
spring.data.mongodb.database: ${MONGO_DATABASE:shared}

management.health.mongo.enabled: false
management.health.reds.enabled: false
management.endpoints.web.exposure.include: health,info 
management.endpoint.health.show-details: never
