version: '3.7'
services:
    mongodb:
        image: mongo
        ports:
            - 27017:27017

    opa:
        image: openpolicyagent/opa:edge-static
        ports:
            - 8181:8181        
        command:
            - run
            - --server
            - /etc/rules/wks_policy_rules.rego
        volumes:
            - ./policy-decision-api:/etc/rules:ro

    camunda:
        image: camunda/camunda-bpm-platform:run-7.19.0-SNAPSHOT
        command: ./camunda.sh --rest --webapps
        ports:
            - 8080:8080
        healthcheck:
            test: curl --fail http://localhost:8080/engine-rest/version || exit 1
            interval: 10s
            retries: 3
            start_period: 5s
            timeout: 10s
        depends_on:
            mongodb:
                condition: service_started

    keycloak:
        image: quay.io/keycloak/keycloak:20.0.3
        command: start-dev --import-realm
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        ports:
            - 8082:8080
        volumes:
            - ./keycloak/realms:/opt/keycloak/data/import
            - ./keycloak/themes:/opt/keycloak/themes

    case-engine-loader:
        build:
            context: case-engine-loader
        environment:
            - CAMUNDA_BASE_URL=http://camunda:8080/engine-rest
            - CAMUNDA_USERNAME=demo
            - CAMUNDA_PASSWORD=demo
            - MONGO_DATABASE=wks-mongo-database
            - MONGO_CONN=mongodb://mongodb
        depends_on:
            mongodb:
                condition: service_started
            camunda:
                condition: service_healthy
       
    case-engine-rest-api:
        build:
            context: case-engine-rest-api
        ports:
            - 8081:8081
        links:
            - mongodb
            - camunda
        environment:
            - MONGO_DATABASE=wks-mongo-database
            - MONGO_CONN=mongodb://mongodb
            - KEYCLOAK_JWKS_SET_URI=http://keycloak:8080
            - OPA_URL=http://opa:8181/v1/data/wks/authz/allow
        depends_on:
            camunda:
                condition: service_healthy

    bpm-engine-c7-external-service:
        build:
            context: bpm-engine-c7-external-service
        links:
            - mongodb
            - camunda
        environment:
            - CAMUNDA_BASE_URL=http://camunda:8080/engine-rest
            - CAMUNDA_USERNAME=demo
            - CAMUNDA_PASSWORD=demo
            - MONGO_DATABASE=wks-mongo-database
            - MONGO_CONN=mongodb://mongodb
        depends_on:
            camunda:
                condition: service_healthy

    email-to-case:
        build:
            context: email-to-case
        ports:
            - 8083:8083
        links:
            - mongodb
            - camunda
        environment:
            - CAMUNDA_BASE_URL=http://camunda:8080/engine-rest
            - CAMUNDA_USERNAME=demo
            - CAMUNDA_PASSWORD=demo
            - MONGO_DATABASE=wks-mongo-database
            - MONGO_CONN=mongodb://mongodb
            - EMAIL_CASE_PATTERN_NEW=new-case
            - EMAIL_CASE_PATTERN_UPDATE=update-case
            - KEYCLOAK_JWKS_SET_URI=http://keycloak:8080
            - OPA_URL=http://opa:8181/v1/data/wks/authz/allow
        depends_on:
            camunda:
                condition: service_healthy

    case-portal-admim:
        build:
            context: case-portal-admin-react
            args:
                REACT_APP_KEYCLOAK_URL: http://localhost:8082
                REACT_APP_API_URL: http://localhost:8081
        ports:
            - 3002:3000

    case-portal:
        build:
            context: case-portal-react
            args:
                REACT_APP_KEYCLOAK_URL: http://localhost:8082
                REACT_APP_API_URL: http://localhost:8081
                REACT_APP_EMAIL_URL: http://localhost:8083
        ports:
            - 3001:3000