version: '3.7'
services:
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        healthcheck:
            test: mongosh --eval 'db.stats().ok' --quiet
            interval: 10s
            retries: 3
            start_period: 5s
            timeout: 10s

    opa:
        image: openpolicyagent/opa:edge-static
        ports:
            - 8181:8181
        # links:
        #     - opa-bundles-service
        command:
            - run
            - --server
            - /etc/rules/wks_policy_rules.rego
        volumes:
            - ./policy-decision-api:/etc/rules

    opa-bundles-service:
        build:
            context: .
            dockerfile: ./policy-decision-api/Dockerfile

    camunda:
        image: camunda/camunda-bpm-platform:run-7.19.0-SNAPSHOT
        command: ./camunda.sh --rest --webapps
        ports:
            - 8080:8080
        healthcheck:
            test: curl --fail http://localhost:8080/engine-rest/version || exit 1
            interval: 10s
            retries: 3
            start_period: 5s
            timeout: 10s
        depends_on:
            mongodb:
                condition: service_healthy

    keycloak:
        image: quay.io/keycloak/keycloak:20.0.3
        command: start-dev
        environment:
            KC_HEALTH_ENABLED: "true"
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        healthcheck:
            test: curl --fail http://localhost:8080/health/ready || exit 1
            interval: 10s
            retries: 3
            start_period: 5s
            timeout: 10s
        ports:
            - 8082:8080
       
    case-engine-rest-api:
        build:
            context: .
            dockerfile: ./case-engine-rest-api/Dockerfile
        ports:
            - 8081:8081
        links:
            - mongodb
            - camunda
        environment:
            - MONGO_DATABASE=wks
            - MONGO_CONN=mongodb://mongodb
            - KEYCLOAK_JWKS_SET_URI=http://keycloak:8080
            - OPA_URL=http://opa:8181/v1/data/wks/authz/allow
        depends_on:
            mongodb:
                condition: service_healthy
            camunda:
                condition: service_healthy
        volumes:
            - cache:/root/.m2

    bpm-engine-c7-external-service:
        build:
            context: .
            dockerfile: ./bpm-engine-c7-external-service/Dockerfile
        links:
            - mongodb
            - camunda
        environment:
            - CAMUNDA_URL=http://camunda:8080/engine-rest
            - CAMUNDA_USERNAME=demo
            - CAMUNDA_PASSWORD=demo
            - MONGO_DATABASE=wks
            - MONGO_CONN=mongodb://mongodb
        depends_on:
            mongodb:
                condition: service_healthy
            camunda:
                condition: service_healthy
        volumes:
            - cache:/root/.m2

    email-to-case:
        build:
            context: .
            dockerfile: ./email-to-case/Dockerfile
        ports:
            - 8083:8083
        links:
            - mongodb
            - camunda
        environment:
            - MONGO_DATABASE=wks
            - MONGO_CONN=mongodb://mongodb
            - EMAIL_CASE_PATTERN_NEW=new-case
            - EMAIL_CASE_PATTERN_UPDATE=update-case
            - KEYCLOAK_JWKS_SET_URI=http://keycloak:8080
            - OPA_URL=http://opa:8181/v1/data/wks/authz/allow
        depends_on:
            mongodb:
                condition: service_healthy
            camunda:
                condition: service_healthy
        volumes:
            - cache:/root/.m2

    case-portal:
        build:
            context: .
            dockerfile: ./case-portal-react/Dockerfile
            args:
                REACT_APP_KEYCLOAK_URL: http://localhost:8082
                REACT_APP_API_URL: http://localhost:8081
                REACT_APP_EMAIL_URL: http://localhost:8083
        environment:
            NODE_OPTIONS: --max_old_space_size=4096
        ports:
            - 3001:3000
        volumes:
            - cache:/node_modules

volumes:
    cache:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/tmp'            