apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: case-engine-rest-api
  name: case-engine-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: case-engine-rest-api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: case-engine-rest-api
    spec:
      containers:
        - env:
            - name: data.import.enabled
              value: "true"
            - name: data.import.folder
              value: /opt/case-engine-sample-data
          image: wks-platform-case-engine-rest-api:latest
          name: case-engine-rest-api
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          resources: {}
          volumeMounts:
            - mountPath: /opt/case-engine-sample-data
              name: case-engine-rest-api-claim0
      restartPolicy: Always
      volumes:
        - name: case-engine-rest-api-claim0
          persistentVolumeClaim:
            claimName: case-engine-rest-api-claim0
status: {}
