spring:
  main:
    allow-circular-references: true
  config:
    import: file:env.properties
  output:
    ansi:
      enabled: ALWAYS

logging:
   level:
      root: WARN
      com:
         mmc: INFO
      org.springframework.web.client.RestTemplate: ERROR
      org.apache.http: ERROR
      httpclient.wire: ERROR

camunda7.rest.oauth.token.uri:
camunda7.rest.oauth.token.clientId:
camunda7.rest.oauth.token.clientSecret:
camunda7.rest.oauth.token.grantType:

camunda7.rest.url: http://${CAMUNDA7_HOST}:${CAMUNDA7_PORT}/engine-rest
camunda7.rest.deployment.url: ${camunda7.rest.url}/deployment
camunda7.rest.processdefinition.url: ${camunda7.rest.url}/process-definition
camunda7.rest.processinstance.url: ${camunda7.rest.url}/process-instance
camunda7.rest.task.url: ${camunda7.rest.url}/task

mmc.bpm.case.generic.process-def-key: ${MMC_BPM_CASE_GENERIC_PROCESS_DEF_KEY}