name: main

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  REPOSITORY_OWNER: wkspower
  KEYCLOAK_URL: http://sts.wkspower.local
  WKS_API_URL: http://api.wkspower.local
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - id: get_version
      uses: battila7/get-version-action@v2

    - name: Set up jdk 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'

    - name: Set up maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build all for backend api
      run: mvn -B package --file pom.xml

    - name: Install dependencies for case-portal-react
      run: yarn --cwd case-portal-react install

    - name: Build for case-portal-react
      run: REACT_APP_KEYCLOAK_URL=${{ env.KEYCLOAK_URL }} REACT_APP_API_URL=${{ env.WKS_API_URL }} yarn --cwd case-portal-react build

    - name: Install dependencies for case-portal-admin-react
      run: yarn --cwd case-portal-admin-react install

    - name: Build for case-portal-admin-react
      run: REACT_APP_KEYCLOAK_URL=${{ env.KEYCLOAK_URL }} REACT_APP_API_URL=${{ env.WKS_API_URL }} yarn --cwd case-portal-admin-react build

    - name: Build and push Docker image for bpm-engine-c7-external-service
      uses: docker/build-push-action@v2
      with:
        context: ./bpm-engine-c7-external-service
        file: bpm-engine-c7-external-service/Dockerfile
        push: true
        tags: "${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/bpm-engine-c7-external-service:${{ steps.get_version.outputs.build }}"

    - name: Build and push Docker image for case-engine-rest-api
      uses: docker/build-push-action@v2
      with:
        context: ./case-engine-rest-api
        file: case-engine-rest-api/Dockerfile
        push: true
        tags: "${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/case-engine-rest-api:${{ steps.get_version.outputs.build }}"

    - name: Build and push Docker image for case-portal-admin-react
      uses: docker/build-push-action@v2
      with:
        context: ./case-portal-admin-react
        file: case-portal-admin-react/deployments/Dockerfile
        push: true
        tags: "${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/case-portal-admin-react:${{ steps.get_version.outputs.build }}"

    - name: Build and push Docker image for case-portal-react
      uses: docker/build-push-action@v2
      with:
        context: ./case-portal-react
        file: case-portal-react/deployments/Dockerfile
        push: true
        tags: "${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/case-portal-react:${{ steps.get_version.outputs.build }}"

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        repository: wkspower/wks-gitops
        path: wks-gitops
        token: ${{ secrets.GH_PAT }}

    - id: get_version
      uses: battila7/get-version-action@v2

    - uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.0.0/kustomize_v5.0.0_linux_amd64.tar.gz'
        name: 'kustomize'
        version: '5.0.0'

    - name: Update kubernetes resources with new tag
      run: |
        cd wks-gitops/apps

        cd case-engine-rest-api/local
        kustomize edit set image caseenginerestapi=${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/case-engine-rest-api:${{ steps.get_version.outputs.build }}
        cd ../../

        cd bpm-engine-c7-external-service/local
        kustomize edit set image bpmenginec7extsvc=${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/bpm-engine-c7-external-service:${{ steps.get_version.outputs.build }}
        cd ../../

    - name: New tag release for continuous delivery
      run: |
        cd wks-gitops
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Release docker tag"
        git push